packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - dotenv@18.0.1
