import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { API_URL, CASABLANCA, fillAndSubmitRequest, loginThroughUi, readBrowserSession, setUpProvider, uniquePhone } from "../support/journeys";
test.use({ geolocation: CASABLANCA, permissions: ["geolocation"] });
test.setTimeout(300_000);
// Phase 11: contrast of the reply quote inside the sender's own bubble.
test("reply quote contrast", async ({ page, request }) => {
  const provider = await setUpProvider(request, uniquePhone("6"), `Quote Pro ${Date.now().toString().slice(-4)}`);
  await loginThroughUi(page, uniquePhone("7"));
  await expect(page).toHaveURL(/\/requests\/new$/, { timeout: 20_000 });
  await fillAndSubmitRequest(page);
  await expect(page.getByTestId("submitted-status")).toContainText("REQUESTED", { timeout: 20_000 });
  const requestId = (await page.getByTestId("submitted-request-id").innerText()).trim();
  const client = await readBrowserSession(page);
  await request.post(`${API_URL}/api/v1/requests/${requestId}/match`, { headers: { Authorization: `Bearer ${client.accessToken}` }, data: { mode: "DIRECT", providerId: provider.profileId } });
  await page.goto(`/requests/${requestId}/match`);
  await page.getByTestId("chat-with-provider-button").first().click({ timeout: 20_000 });
  await expect(page).toHaveURL(/\/conversations\//, { timeout: 20_000 });
  await page.getByTestId("composer-input").fill("Premier message");
  await page.getByTestId("send-button").click();
  await expect(page.getByTestId("message-item")).toHaveCount(1, { timeout: 10_000 });
  await page.getByTestId("reply-button").first().click();
  await page.getByTestId("composer-input").fill("Une reponse");
  await page.getByTestId("send-button").click();
  await expect(page.getByTestId("message-item")).toHaveCount(2, { timeout: 10_000 });
  await page.setViewportSize({ width: 1440, height: 900 });
  const r = await new AxeBuilder({ page }).withRules(["color-contrast"]).analyze();
  const out = r.violations.flatMap((v) => v.nodes.map((n) => `${n.target.join(" ")}: ${(n.failureSummary ?? "").split("\n")[1]?.trim() ?? ""}`));
  console.log(JSON.stringify(out, null, 2));
  await page.locator(".fx-reply-quote").first().screenshot({ path: `../../docs/design/evidence/phase11/${process.env.SHOT ?? "AVANT"}-citation.png` });
  await request.patch(`${API_URL}/api/v1/providers/me/availability`, { headers: { Authorization: `Bearer ${provider.session.accessToken}` }, data: { status: "OFFLINE" } });
});
