import { v7 as uuidv7, validate as uuidValidate, version as uuidVersion } from "uuid";

/**
 * Generates a UUIDv7 (time-ordered, RFC 9562) — the distributed identifier
 * format required by 01_SPEC_PRODUCT.md #43. Time-ordering keeps index
 * locality in MongoDB compared to random UUIDv4.
 */
export function generateId(): string {
  return uuidv7();
}

/** True when `value` is a syntactically valid UUID of any version. */
export function isValidId(value: string): boolean {
  return uuidValidate(value);
}

/** True when `value` is specifically a UUIDv7 generated by {@link generateId}. */
export function isValidUuidV7(value: string): boolean {
  return uuidValidate(value) && uuidVersion(value) === 7;
}
