import type { DeviceInput } from "@fixiyi/contracts";
import { generateId } from "@fixiyi/shared-utils";
import { Injectable } from "@nestjs/common";
import { InjectModel } from "@nestjs/mongoose";
import type { Model } from "mongoose";

import { DeviceEntity, type DeviceDocument } from "../schemas/device.schema.js";
import { UserSessionEntity, type UserSessionDocument, type SessionRevokedReason } from "../schemas/user-session.schema.js";

export interface RequestContext {
  ip: string | null;
  userAgent: string | null;
}

export interface CreatedSession {
  deviceId: string;
}

export type RotateResult =
  | { status: "success"; session: UserSessionDocument }
  | { status: "not_found" }
  | { status: "revoked" }
  | { status: "expired" }
  | { status: "reuse_detected" };

/**
 * Persistence + rotation-state for `UserSession`/`Device` (02_SPEC_ENGINEERING.md
 * #98). Deliberately doesn't sign or verify JWTs (`TokenService`'s job) or
 * know about `User` (`AuthService`'s job) — only the session/device state
 * machine: create, rotate, revoke, list.
 */
@Injectable()
export class SessionService {
  constructor(
    @InjectModel(UserSessionEntity.name) private readonly sessionModel: Model<UserSessionEntity>,
    @InjectModel(DeviceEntity.name) private readonly deviceModel: Model<DeviceEntity>,
  ) {}

  /**
   * `sessionId` is generated by the caller (`AuthService`) *before* this
   * call, because the refresh/access JWTs embed it as the `sid` claim and
   * must be signed first to learn `expiresAt` (mirrored from the refresh
   * token's real `exp`) — signing needs the id, so the id can't be Mongo's
   * own `create()`-assigned one.
   */
  async createSession(sessionId: string, userId: string, device: DeviceInput | undefined, context: RequestContext, expiresAt: Date): Promise<CreatedSession> {
    const deviceDoc = await this.upsertDevice(userId, device, context);
    const now = new Date();

    await this.sessionModel.create({
      _id: sessionId,
      userId,
      deviceId: deviceDoc._id,
      tokenVersion: 0,
      status: "ACTIVE",
      ip: context.ip,
      userAgent: context.userAgent,
      lastUsedAt: now,
      expiresAt,
    });

    return { deviceId: deviceDoc._id };
  }

  /** Validates `presentedTokenVersion` against the stored one and, on success, bumps it (rotation). */
  async rotate(sessionId: string, presentedTokenVersion: number, context: RequestContext): Promise<RotateResult> {
    const session = await this.sessionModel.findById(sessionId);
    if (!session) {
      return { status: "not_found" };
    }
    if (session.status === "REVOKED") {
      return { status: "revoked" };
    }
    if (session.expiresAt.getTime() <= Date.now()) {
      return { status: "expired" };
    }
    if (session.tokenVersion !== presentedTokenVersion) {
      // A refresh token whose `rtv` no longer matches was already rotated away —
      // presenting it again means it leaked. Revoke on sight (01_SPEC_PRODUCT.md #70).
      session.status = "REVOKED";
      session.revokedAt = new Date();
      session.revokedReason = "REUSE_DETECTED";
      await session.save();
      return { status: "reuse_detected" };
    }

    session.tokenVersion += 1;
    session.lastUsedAt = new Date();
    session.ip = context.ip ?? session.ip;
    session.userAgent = context.userAgent ?? session.userAgent;
    await session.save();
    return { status: "success", session };
  }

  async findActiveById(sessionId: string): Promise<UserSessionDocument | null> {
    return this.sessionModel.findOne({ _id: sessionId, status: "ACTIVE" });
  }

  /**
   * Which of these sessions are still ACTIVE — one query for any number of
   * ids. Lets a long-lived connection (the chat socket) honour a remote
   * logout the way `AuthGuard` does per HTTP request, without a database
   * round trip per connected socket.
   */
  async filterActiveIds(sessionIds: string[]): Promise<Set<string>> {
    if (sessionIds.length === 0) {
      return new Set();
    }
    const active = await this.sessionModel.find({ _id: { $in: sessionIds }, status: "ACTIVE" }).select("_id");
    return new Set(active.map((session) => session._id));
  }

  async touchLastUsed(sessionId: string): Promise<void> {
    await this.sessionModel.updateOne({ _id: sessionId }, { $set: { lastUsedAt: new Date() } });
  }

  async revoke(sessionId: string, reason: SessionRevokedReason): Promise<void> {
    await this.sessionModel.updateOne(
      { _id: sessionId, status: "ACTIVE" },
      { $set: { status: "REVOKED", revokedAt: new Date(), revokedReason: reason } },
    );
  }

  async revokeAllForUser(userId: string, reason: SessionRevokedReason, exceptSessionId?: string): Promise<void> {
    const filter: Record<string, unknown> = { userId, status: "ACTIVE" };
    if (exceptSessionId) {
      filter._id = { $ne: exceptSessionId };
    }
    await this.sessionModel.updateMany(filter, { $set: { status: "REVOKED", revokedAt: new Date(), revokedReason: reason } });
  }

  async listActiveForUser(userId: string): Promise<UserSessionDocument[]> {
    return this.sessionModel.find({ userId, status: "ACTIVE" }).sort({ lastUsedAt: -1 });
  }

  async getDevicesByIds(deviceIds: string[]): Promise<Map<string, DeviceDocument>> {
    const devices = await this.deviceModel.find({ _id: { $in: deviceIds } });
    return new Map(devices.map((device) => [device._id, device]));
  }

  private async upsertDevice(userId: string, device: DeviceInput | undefined, context: RequestContext): Promise<DeviceDocument> {
    const now = new Date();
    if (device?.id) {
      const existing = await this.deviceModel.findOne({ _id: device.id, userId });
      if (existing) {
        existing.lastSeenAt = now;
        existing.lastSeenIp = context.ip;
        existing.userAgent = context.userAgent;
        if (device.name) {
          existing.name = device.name;
        }
        await existing.save();
        return existing;
      }
    }

    return this.deviceModel.create({
      _id: device?.id ?? generateId(),
      userId,
      name: device?.name ?? null,
      userAgent: context.userAgent,
      lastSeenIp: context.ip,
      lastSeenAt: now,
    });
  }
}
